VDYP-171 Sindxdll
bcgov/VDYP pull request #22
Opened 2023-07-25 20:37 UTC by ehuber03

2023-08-09 17:55 UTC, eddeen commented on vdyp-core/src/main/java/ca/bc/gov/nrs/vdyp/common_calculators/SiteIndex2Height.java
Are these constants missing from the original?

2023-08-09 18:06 UTC, eddeen requested changes
Considering the number of switch statements and if then else's, I think we need some JUnit tests to make sure it is returning what we think it should be returning for specific cases.  Perhaps a discussion about this on how much we should be JUnit testing this specific dll.

2023-08-09 18:31 UTC, ehuber03 commented on vdyp-core/src/main/java/ca/bc/gov/nrs/vdyp/common_calculators/SiteIndex2Height.java
In the original these constants are all surrounded by ifdef statements, as far as I can see they are missing since they are not in sindex.h and cause errors when removed from the ifdef block. Obviously since they are undefined this would get skipped at compile time in C, as far as I'm aware no real easy alternatives exist in Java hence why I removed them. It may be worth questioning why these constants are included in the original if they're never used.

2023-08-31 22:36 UTC, smithkm commented
The duplication SonarCloud is complaining about seems to be multiline strings containing documentation that share lines.  Putting hte shared lines in constants probably doesn't make sense here.  We could suppress the error or move the documentation stings into a data file (JSON, Properties, whatever, and load it at runtime)

2023-09-12 18:29 UTC, eddeen approved these changes
Looks complete.

2023-09-12 18:30 UTC, merged