VDYP-176 VRIStart data parsing
bcgov/VDYP pull request #34
Opened 2024-03-06 17:20 UTC by smithkm

2024-03-12 20:57 UTC, smithkm commented
#33 included a change to the formatter but did not apply the changes.  This PR did apply the formatter leading to lots of unrelated formatting changes, mostly comment text reflowing to use the larger width. I've made PR #35 that just applies those changes.  Merging that first should make this PR much more manageable for review.

2024-04-10 21:41 UTC, mjunkin requested changes

2024-04-10 21:41 UTC, mjunkin commented on vdyp-vri/src/test/java/ca/bc/gov/nrs/vdyp/vri/VriStart.java
> +	protected BaseControlParser getControlFileParser() {
Is it intended that this returns null, or have you just not gotten to writing an implementation?

2024-04-10 22:17 UTC, smithkm commented on vdyp-fip/src/main/java/ca/bc/gov/nrs/vdyp/fip/model/FipLayer.java
> +	// TODO move to FipSite
Something I moved.

2024-04-10 22:39 UTC, smithkm commented on vdyp-common/src/main/java/ca/bc/gov/nrs/vdyp/application/VdypStartApplication.java
> +	public void setControlMap(Map<String, Object> controlMap) {
That was visible for some unit tests.  I've made it package visible and created a utility method to allow tests in other packages to manipulate it.

2024-04-10 23:19 UTC, mjunkin approved these changes

2024-04-10 23:19 UTC, merged